CREATE TABLE user (
  id INT AUTO_INCREMENT PRIMARY KEY,
  pseudo VARCHAR(150) NOT NULL,
  email VARCHAR(250) NOT NULL UNIQUE,
  password VARCHAR(250) NOT NULL,
  city VARCHAR(150),
  country VARCHAR(150),
  adress VARCHAR(250),
  registration_date DATETIME NOT NULL DEFAULT NOW(),
  isAdmin BOOLEAN DEFAULT 0
);